import Curve from '@/components/Layout/Curve'
import Head from 'next/head'
import Stairs from '@/components/Layout/Stairs'
import { useScrollPercentage } from 'react-scroll-percentage'
import { motion, stagger } from 'framer-motion'
import AnimatedText from '@/components/animatedText'

export default function About() {
    const [ref, percentage] = useScrollPercentage({
    threshold: 0,
  })
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stairs backgroundColor={"#BCF366"}>
      
      <main className="flex min-h-screen flex-col items-center justify-between text-6xl text-slate-900 bg-neutral-900 overflow-clip hover:overflow-y-visible">
      <div className="flex items-center h-screen w-screen justify-center bg-white p-6">
        {/* <Tooltip text="Name" gifUrl={gifUrl}> */}
          {/* <motion.span initial={{y:20, opacity:0}} animate={{y:0, opacity:1}} transition={{ staggerChildren: 0.7}} ref={ref} className="font-serif font-semibold uppercase text-10xl text-black" style={{ opacity: (0.8 - percentage) * 2 }}>
            {"ABOUT".split("").map((char) => (
              <motion.span >{char}</motion.span>
            ))}
          </motion.span> */}
          <span ref={ref} style={{ opacity: (0.8 - percentage) * 2 }}>
         <AnimatedText text={"ABOUT"} className={"font-serif font-semibold uppercase text-10xl text-black"}/>
         </span>
        {/* </Tooltip> */}
      </div>
      </main>
      </Stairs>
    </>
  )
}
