import Curve from '@/components/Layout/Curve'
import Head from 'next/head'
import Stairs from '@/components/Layout/Stairs'
import { useRouter } from 'next/navigation'
import { useParams } from 'next/navigation'
import { CarouselClick } from '@/components/CarouselClick'
// import { projects } from './constants'
import { EmblaCarousel } from '@/components/EmblaCarousel'
import { cards, projects } from '@/constants'
import ContactUs from '@/components/contactUs'


export default function Projects() {
    const params = useParams()
    const router = useRouter()

    var header = params ? params.projectIds : "contract_commitments";

    const nextProject = findNextProject(header, cards);
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Stairs backgroundColor="#FFF">
                <main className="flex min-h-screen w-screen flex-col items-center justify-between text-slate-900 bg-black overflow-clip hover:overflow-y-visible">
                    {
                        (projects[header]["before"] ? projects[header]["before"] : []).map((element) => {
                            return (
                                <div className='pt-60 p-20 w-screen text-black font-exo bg-white height-screen text-center'>
                                    <span className='text-xl p-12 text-center justify-center w-full'> {element.header} </span>
                                    <div className='w-full text-left text-4xl p-12 font-normal leading-normal'>
                                        {element.description}
                                    </div>
                                </div>
                            )
                        })
                    }
                    <div className='w-full bg-white'>
                        <EmblaCarousel imgList={projects[header] ? projects[header]["imgs"] : []} />
                    </div>
                    {
                        (projects[header]["after"] ? projects[header]["after"] : []).map((element) => {
                            return (
                                <div className='pt-60 p-20 w-screen text-black font-exo bg-white height-screen text-center'>
                                    <span className='text-xl p-12 text-center justify-center w-full'> {element.header} </span>
                                    <div className='w-full text-left text-4xl p-12 font-normal leading-normal'>
                                        {element.description}
                                    </div>
                                </div>
                            )
                        })
                    }
                    <div className='pt-20 p-20 w-screen text-black font-exo bg-white height-screen text-center'>
                        <span className='text-xl p-12 text-center justify-center w-full'> GO TO NEXT PROJECT PLEASE CLICK BELOW (ASK GEN AI) </span>

                    </div>
                    <div className='h-screen w-screen bg-white justify-center rounded-b-10xl' style={{ textAlign: "-webkit-center" }}>
                        <div
                            key={nextProject.id}
                            className="group relative h-[80vh] w-[80vh] overflow-hidden bg-neutral-200 rounded-3xl cursor-pointer"
                            style={{ border: "1px solid #555" }}
                            onClick={() => router.push(nextProject.link)}
                        >
                            <div
                                style={{
                                    backgroundColor: "blue",
                                    backgroundImage: `url(${nextProject.url})`,
                                    backgroundSize: "cover",
                                    backgroundPosition: "center",
                                }}
                                className="absolute opacity-100 inset-0 z-0 transition-opacity duration-500 group-hover:opacity-0"
                            ></div>
                            <div
                                style={{
                                    backgroundColor: "blue",
                                    backgroundImage: `url(${nextProject.url2})`,
                                    backgroundSize: "cover",
                                    backgroundPosition: "center",
                                }}
                                className="absolute opacity-0 inset-0 z-0 transition-opacity duration-500 group-hover:opacity-100"
                            ></div>

                        </div>
                    </div>
                    <div className="flex h-threequarter w-full items-center justify-center">
                        <ContactUs />
                    </div>
                </main>
            </Stairs>
        </>
    )
}

const findNextProject = (current, allCards) => {
    let position = 0;
    allCards.map((element, index) => {
        if (element.title == current) {
            if (index == (allCards.length - 1)) {
                position = 0;
            }
            else {
                position = index + 1
            }
        }
    })
    return allCards[position]
}