import Curve from '@/components/Layout/Curve'
import Head from 'next/head'
import Stairs from '@/components/Layout/Stairs'
import { useScrollPercentage } from 'react-scroll-percentage'
import AnimatedText from '@/components/animatedText'

import HorizontalScrollCarousel from '@/components/HorizontalCarousel';
import ImgGrid from '@/components/ImgGrid';
import ProjectsGrid from '@/components/projectsGrid'
import ContactUs from '@/components/contactUs'


export default function Projects() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stairs backgroundColor={"#BCF366"}>
<main className="flex min-h-screen font-exo flex-col items-center justify-between text-6xl text-slate-900 bg-black overflow-clip hover:overflow-y-visible" style={{zIndex: -3}}>
          <div className=" bg-white rounded-b-10xl" style={{zIndex: 1}}>
          <div className='relative h-img w-full bg-white rounded-b-10xl'>
            <ProjectsGrid />
            <div className="flex items-end h-screen w-screen justify-center bg-white p-6 absolute sticky top-0 rounded-b-10xl">
              <span>
                <AnimatedText text={"WORK"} className={"font-serif font-medium uppercase text-10xl text-black"} italic={"O"} />
              </span>
            </div>
          </div>
          </div>
          <ContactUs/>
          
        </main>
      </Stairs>
    </>
  )
}
